In [1]:
import numpy as np

### ARRAY OPERATIONS

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [3]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [4]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [5]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1 // a2

array([0, 0, 0, 0, 0])

In [8]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

### Broadcasting

In [9]:
l = [10,20,30,40]
arr = np.array(l)

In [10]:
arr + 10

array([20, 30, 40, 50])

### Deep and Shallow copy

In [11]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [14]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
b = a #Deep copy
b = a.copy() #shallow copy

### Matrix Operation

In [17]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [18]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [19]:
A.T

array([[1, 3],
       [2, 4]])

### Advance Array Manipulation

#### Stacking Array

In [20]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [21]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#### Splitting Array

In [24]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [26]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]