In [1]:
import numpy as np

### Basic Array Creation

In [4]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
a = [1,2,3.5, "hello"]
a

[1, 2, 3.5, 'hello']

In [8]:
np.array(a) #converts in string all element

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [11]:
a = [1, 2, 3.5]
np.array(a) #converts in float all element

array([1. , 2. , 3.5])

In [13]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l #list does not supports multi-dimension

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(l) #numpy supports multi-dimension

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array generation function

In [17]:
np.arange(1,11,2) #1 to 10 steps 2

array([1, 3, 5, 7, 9])

In [25]:
arr = np.zeros((6,5)) #single value gives array ... for matrix(row,col)
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [24]:
arr = np.linspace(1,5,2) #1to5 2elements linear space
arr

array([1., 5.])

### Random Generation function

In [29]:
np.random.rand(10) #vector
# value between 0 and 1

array([0.52471669, 0.00747474, 0.58715223, 0.9938756 , 0.59164501,
       0.87079051, 0.9156947 , 0.79389807, 0.28553053, 0.55183308])

In [36]:
np.random.randint(6) #0 to n
np.random.randint(10,20)  #10 to 20
np.random.randint(10,20,10)  #10 to 20 ==> 10 numbers

array([17, 11, 17, 16, 16, 11, 19, 16, 10, 10], dtype=int32)

### Array Attributes

In [37]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr.shape

(3, 3)

In [39]:
arr.size

9

In [40]:
arr.dtype

dtype('int64')

### Array Methods

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.min()

np.int64(1)

In [43]:
arr.max()

np.int64(9)

In [44]:
arr.sum()

np.int64(45)

In [47]:
np.sum(arr,axis=1) #col=0 Row=1

array([ 6, 15, 24])

In [48]:
arr.mean()

np.float64(5.0)

In [49]:
arr.std()

np.float64(2.581988897471611)

In [50]:
arr.argmax()

np.int64(8)

In [51]:
arr.argmin()

np.int64(0)

### Reshaping and resizing

In [53]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [56]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])