In [1]:
import numpy as np

### NUMPY INDEXING AND SLICING OF VECTORS

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[3:6] # index x to n-1
arr[:6] # start to 6
arr[3:] #3 to end
arr[3::2] # 3to end steps = 2

array([14, 16, 18, 20])

### NUMPY INDEXING AND SLICING OF MATRIX

In [7]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr[0,0] # row,col

np.int64(1)

In [16]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [17]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

### BOOLEAN INDEXING

In [18]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
bool_index = arr%2 == 0
bool_index


array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [20]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])